### ISSUE TITLE
Fortune Resource Filter is not working

### ISSUE THREAD

**Issue by StefanSchubert** [oboehm/jfortune#1]
Hi there,

first thanks for jfortune. It remembers me of the old times and I would like to use it in a fun application (IoT doorbell),
however when trying to fetch a cookie I got a:

`Caused by: java.lang.IllegalArgumentException: cannot reed cookies from /fortunes/sprichworte`

I was using 

`static Fortune fortune = new Fortune(Locale.GERMAN, "sprichworte");`

to initialize the provider.

The access path looks like, the Locale is ignored and thus the resource is not found.

Cheers 
Stefan

**Comment by oboehm** [comment]
Ah, yes, the good times in the beginning of the EPOCH ;-)
I can reproduce the error so I will take a look at it. And yes, you're right, the Locale is ignored - i will fix it.

**Comment by StefanSchubert** [comment]
Hi - I'm on it I take it as exercise for my first github merge request. Wait 5 min...

**Comment by oboehm** [comment]
Ok - sound`s good. As workaround you can also use

        Fortune fortune = new Fortune(Locale.GERMAN, "de/sprichworte");

**Comment by StefanSchubert** [comment]
If I did it right you should received a merge request by now. It was a quick fix, I assume this could be accomplished a bit nicer.

**Comment by oboehm** [comment]
version 0.6 of jfortune was just released now - thanx for the fix
